from typing import Optional, Union
"""add_missing_model_columns

Revision ID: 4cd8c3d374d8
Revises: a9aa4524abd7
Create Date: 2026-09-14 01:58:32.647293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cd8c3d374d8"
down_revision: Union[str, Sequence[str]] = "a9aa4524abd7"
branch_labels: Union[str, Sequence[str]] = None
depends_on: Union[str, Sequence[str]] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("requester", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("cost", sa.String(), nullable=True),
        sa.Column("expected_return", sa.String(), nullable=True),
        sa.Column("risk", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=True),
        sa.Column("customer", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("companies", sa.Column("settings", sa.JSON(), nullable=True))
    op.add_column("companies", sa.Column("org_hierarchy", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "org_hierarchy")
    op.drop_column("companies", "settings")
    op.drop_table("financial_transactions")
    op.drop_table("approvals")
    # ### end Alembic commands ###
