"""expand_agent_task_models

Revision ID: 655f59f984df
Revises: 4cd8c3d374d8
Create Date: 2026-09-17 00:49:13.572341

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655f59f984df'
down_revision: Union[str, Sequence[str], None] = '4cd8c3d374d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('runtime_type', sa.String(), nullable=True),
    sa.Column('autonomy_level', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('owner_agent_id', sa.UUID(), nullable=True),
    sa.Column('parent_goal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reasoning_model_id', sa.String(), nullable=True),
    sa.Column('execution_model_id', sa.String(), nullable=True),
    sa.Column('fast_model_id', sa.String(), nullable=True),
    sa.Column('vision_model_id', sa.String(), nullable=True),
    sa.Column('embedding_model_id', sa.String(), nullable=True),
    sa.Column('fallback_model_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('span_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_goal_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('input_cost_per_1k', sa.Float(), nullable=True),
    sa.Column('output_cost_per_1k', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('input_args', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('model_id', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('runtime_type', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('autonomy_level', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('token_budget', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('cost_budget', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('parent_department_id', sa.UUID(), nullable=True))
    op.add_column('departments', sa.Column('head_agent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'departments', 'departments', ['parent_department_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'agents', ['head_agent_id'], ['id'])
    op.add_column('events', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('causation_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('source', sa.String(), nullable=True))
    op.add_column('events', sa.Column('actor_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('token_usage', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'correlation_id')
    op.drop_column('tasks', 'error')
    op.drop_column('tasks', 'cost')
    op.drop_column('tasks', 'token_usage')
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'acceptance_criteria')
    op.drop_column('tasks', 'expected_outcome')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'department_id')
    op.drop_column('tasks', 'company_id')
    op.drop_column('events', 'actor_type')
    op.drop_column('events', 'source')
    op.drop_column('events', 'causation_id')
    op.drop_column('events', 'correlation_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_agent_id')
    op.drop_column('departments', 'parent_department_id')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'display_name')
    op.drop_column('agents', 'icon')
    op.drop_column('agents', 'cost_budget')
    op.drop_column('agents', 'token_budget')
    op.drop_column('agents', 'autonomy_level')
    op.drop_column('agents', 'runtime_type')
    op.drop_column('agents', 'model_id')
    op.drop_column('agents', 'instructions')
    op.drop_column('agents', 'system_prompt')
    op.drop_table('tool_calls')
    op.drop_table('agent_steps')
    op.drop_table('models')
    op.drop_table('goal_dependencies')
    op.drop_table('agent_runs')
    op.drop_table('model_providers')
    op.drop_table('model_policies')
    op.drop_table('goals')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
